"""
Pipeline RL training loop backed by FSDP data parallelism.

Rollouts are generated by the vLLM worker, scored by the environment, and
accumulated in a ReplayBuffer.  Once a full batch is ready the trainer runs
one gradient update using the loss function selected by ``cfg.algorithm``
(grpo / dapo / reinforce / gspo / cispo / maxrl — see loss.py).

Every ``cfg.stale_steps`` trainer updates the current weights are pushed
into the vLLM worker in-place via NCCL so it never drifts more than K
steps behind the policy.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any

import torch
import torch.distributed as dist
import torch.nn as nn
from loguru import logger
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from transformers import AutoModelForCausalLM, AutoTokenizer

from scale_rl.inference.rollout import (
    generate_rollouts_remote,
    get_logprobs,
    prepare_batch,
    remote_vllm_init_weight_transfer,
    sync_weights_to_vllm_inplace,
    wait_for_rollout_worker,
)
from scale_rl.replay_buffer import ReplayBuffer
from scale_rl.trainer.dp_utils import prepare_dp_model
from scale_rl.trainer.loss import ALGORITHMS, compute_advantages
from scale_rl.trainer.config import TrainerConfig




# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------

class Trainer:
    """
    Owns the FSDP model, optimizer, replay buffer, and the NCCL group used
    to push weights into the vLLM rollout worker.

    Parameters
    ----------
    cfg:
        ``TrainerConfig`` instance.
    device_mesh:
        ``DeviceMesh`` constructed before calling ``__init__``, e.g.::

            mesh = dist.device_mesh.init_device_mesh("cuda", (world_size,))
    model_update_group:
        NCCL process group shared between trainer ranks and the vLLM worker.
        Build with ``dist.new_group([...])`` after ``dist.init_process_group``.
    """

    def __init__(
        self,
        cfg: TrainerConfig,
        device_mesh: Any,
        model_update_group: Any,
    ) -> None:
        self.cfg = cfg
        self.device = torch.device("cuda", int(os.environ.get("LOCAL_RANK", 0)))
        self.rank = int(os.environ.get("RANK", 0))

        self.tokenizer = AutoTokenizer.from_pretrained(cfg.model_path)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        base_model = AutoModelForCausalLM.from_pretrained(
            cfg.model_path,
            torch_dtype=getattr(torch, cfg.dtype),
        )
        self.model: FSDP = prepare_dp_model(
            base_model,
            dtype=cfg.dtype,
            sync_module_states=cfg.sync_module_states,
            device_mesh=device_mesh,
        )

        self.optimizer = torch.optim.AdamW(
            self.model.parameters(),
            lr=cfg.lr,
            weight_decay=cfg.weight_decay,
        )

        self.model_update_group = model_update_group

        self.buffer = ReplayBuffer(
            prompts_per_batch=cfg.prompts_per_batch,
            rollouts_per_step=cfg.rollouts_per_step,
            stale_steps=cfg.stale_steps,
            rollout_worker_url=cfg.rollout_worker_url,
        )

        if cfg.algorithm not in ALGORITHMS:
            raise ValueError(
                f"Unknown algorithm {cfg.algorithm!r}. "
                f"Choose from: {list(ALGORITHMS)}"
            )
        self._loss_fn = ALGORITHMS[cfg.algorithm]

    # ------------------------------------------------------------------
    # Single gradient update
    # ------------------------------------------------------------------

    def step(self, batch: dict[str, Any]) -> dict[str, float]:
        """
        Run one gradient update from a buffer batch.

        Parameters
        ----------
        batch:
            Dict returned by ``ReplayBuffer.sample()``:
            ``{"rollouts": [...], "rewards": [...]}``.

        Returns
        -------
        Metrics dict (loss + algorithm-specific diagnostics).
        """
        cfg = self.cfg

        rewards = torch.tensor(batch["rewards"], dtype=torch.float32, device=self.device)
        advantages = compute_advantages(
            cfg.algorithm,
            rewards,
            num_samples_per_prompt=cfg.rollouts_per_step,
        )

        tensors = prepare_batch(
            batch["rollouts"],
            batch["rewards"],
            self.tokenizer,
            cfg.max_seq_len,
            self.device,
        )

        self.optimizer.zero_grad()

        # Current policy log-probs [B, T-1] and aligned response mask.
        logprobs, response_mask = get_logprobs(
            self.model,
            tensors["input_ids"],
            tensors["attention_mask"],
            tensors["response_mask"],
        )

        loss = self._loss_fn(
            logprobs=logprobs,
            old_logprobs=tensors["inference_logprobs"],
            advantages=advantages,
            response_mask=response_mask,
            # algorithm-specific kwargs (unused ones are swallowed by **kwargs)
            clip=cfg.clip_eps,
            clip_low=cfg.clip_low,
            clip_high=cfg.clip_high,
            kl_coeff=cfg.kl_coef,
            inference_logprobs=tensors["inference_logprobs"],
            C=cfg.tis_C,
        )

        loss.backward()
        nn.utils.clip_grad_norm_(self.model.parameters(), cfg.max_grad_norm)
        self.optimizer.step()

        with torch.no_grad():
            ratio = (logprobs - tensors["inference_logprobs"]).exp()
            mask = response_mask.float()
            n_tok = mask.sum().clamp(min=1)
            clip_frac = (
                ((ratio < 1 - cfg.clip_eps) | (ratio > 1 + cfg.clip_eps))
                .float().mul(mask).sum() / n_tok
            ).item()

        metrics = {
            "loss": loss.item(),
            "clip_frac": clip_frac,
            "mean_reward": rewards.mean().item(),
        }

        if self.rank == 0:
            logger.info(
                "[trainer step {step}] loss={loss:.4f}  clip_frac={clip_frac:.3f}"
                "  mean_reward={mean_reward:.4f}  algorithm={algo}",
                step=self.buffer.trainer_steps + 1,  # +1: incremented inside on_trainer_step
                loss=metrics["loss"],
                clip_frac=metrics["clip_frac"],
                mean_reward=metrics["mean_reward"],
                algo=cfg.algorithm,
            )

        synced = self.buffer.on_trainer_step(
            self.model,
            self.model_update_group,
            packed=cfg.weight_transfer_packed,
            fsdp=True,
        )
        if synced and self.rank == 0:
            logger.info(
                "[weight sync] trainer step {step} → vLLM  "
                "(every {k} steps, packed={packed}, fsdp={fsdp})",
                step=self.buffer.trainer_steps,
                k=cfg.stale_steps,
                packed=cfg.weight_transfer_packed,
                fsdp=True,
            )

        return metrics

    # ------------------------------------------------------------------
    # Full training loop
    # ------------------------------------------------------------------

    def train(self, envs: list[Any], prompts: list[str]) -> None:
        """
        End-to-end training loop.

        Parameters
        ----------
        envs:
            ``ScaleRLBase`` environment instances — one per entry in ``prompts``.
            Used only for reward computation.
        prompts:
            Raw text prompts cycled through during training.
        """
        cfg = self.cfg
        assert len(envs) == len(prompts), "envs and prompts must be the same length"

        if self.rank == 0:
            wait_for_rollout_worker(cfg.rollout_worker_url)

        if self.rank == 0:
            remote_vllm_init_weight_transfer(
                cfg.rollout_worker_url,
                master_address=cfg.master_address,
                master_port=cfg.master_port,
                rank_offset=dist.get_world_size(),
                world_size=dist.get_world_size() + 1,
            )

        # Push initial weights into vLLM before any rollout is collected.
        sync_weights_to_vllm_inplace(
            self.model,
            cfg.rollout_worker_url,
            self.model_update_group,
            packed=cfg.weight_transfer_packed,
            fsdp=True,
        )

        global_step = 0
        prompt_idx = 0
        # Build the active pool — envs flagged high_pass_rate are excluded.
        active_indices = [i for i, e in enumerate(envs) if not e.high_pass_rate]
        HIGH_PASS_THRESHOLD = cfg.high_pass_rate_threshold

        while global_step < cfg.total_steps:
            # Refresh active pool each round (flags may have been set last round).
            active_indices = [i for i, e in enumerate(envs) if not e.high_pass_rate]
            if not active_indices:
                if self.rank == 0:
                    logger.warning(
                        "All {} prompts have high_pass_rate=True — nothing left to train on.",
                        len(envs),
                    )
                break

            # ---- generate rollouts (rank 0 drives the HTTP call) ----
            # Cycle through the active pool only.
            n_active = len(active_indices)
            batch_indices = [
                active_indices[(prompt_idx + i) % n_active]
                for i in range(cfg.prompts_per_batch)
            ]
            batch_prompts = [prompts[i] for i in batch_indices]
            batch_envs   = [envs[i]    for i in batch_indices]
            prompt_idx   += cfg.prompts_per_batch

            if self.rank == 0:
                rollouts = generate_rollouts_remote(
                    cfg.rollout_worker_url,
                    batch_prompts,
                    num_samples=cfg.rollouts_per_step,
                    max_new_tokens=cfg.max_new_tokens,
                    temperature=cfg.temperature,
                    top_k=cfg.top_k,
                )
                # Rollouts are ordered: [prompt_0 × G, prompt_1 × G, ...]
                rewards: list[float] = []
                for i, env in enumerate(batch_envs):
                    group_rewards: list[float] = []
                    for g in range(cfg.rollouts_per_step):
                        r = rollouts[i * cfg.rollouts_per_step + g]["response"]
                        reward, _ = env.compute_reward(r)
                        rewards.append(reward)
                        group_rewards.append(reward)

                    # Mark env if binary pass rate >= threshold.
                    pass_rate = sum(group_rewards) / len(group_rewards)
                    if pass_rate >= HIGH_PASS_THRESHOLD and not env.high_pass_rate:
                        env.high_pass_rate = True
                        logger.info(
                            "[high_pass_rate] prompt idx={idx} marked — "
                            "pass_rate={rate:.2f} >= {thresh:.2f}, will be skipped henceforth.",
                            idx=batch_indices[i],
                            rate=pass_rate,
                            thresh=HIGH_PASS_THRESHOLD,
                        )

                newly_filtered = sum(1 for e in envs if e.high_pass_rate)
                logger.info(
                    "[high_pass_rate] {filtered}/{total} prompts filtered out so far.",
                    filtered=newly_filtered,
                    total=len(envs),
                )

                self.buffer.add(rollouts, rewards)

            # Ensure all ranks wait for rank-0 to finish collecting.
            dist.barrier()

            # ---- drain the buffer ----
            while self.buffer.is_ready():
                batch = self.buffer.sample()
                metrics = self.step(batch)
                global_step += 1

                if self.rank == 0 and global_step % cfg.log_every == 0:
                    logger.info(
                        "step=%d  loss=%.4f  clip_frac=%.3f  mean_reward=%.4f",
                        global_step,
                        metrics["loss"],
                        metrics["clip_frac"],
                        metrics["mean_reward"],
                    )

                if global_step >= cfg.total_steps:
                    break
