"""
Pipeline RL training loop backed by FSDP data parallelism.

Rollouts are generated by the vLLM worker, scored by the environment, and
accumulated in a ReplayBuffer.  Once a full batch is ready the trainer runs
one gradient update using the loss function selected by ``cfg.algorithm``
(grpo / dapo / reinforce / gspo / cispo / maxrl — see loss.py).

Every ``cfg.stale_steps`` trainer updates the current weights are pushed
into the vLLM worker in-place via NCCL so it never drifts more than K
steps behind the policy.
"""

from __future__ import annotations

import asyncio
import os
from dataclasses import dataclass
from typing import Any

import torch
import torch.distributed as dist
import torch.nn as nn
import wandb
from loguru import logger
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from transformers import AutoModelForCausalLM, AutoTokenizer

from scale_rl.algos.loss import ALGORITHMS, compute_advantages
from scale_rl.algos.utils import get_logprobs, prepare_batch
from scale_rl.envs import DATASET_ENV_CLS
from scale_rl.inference.rollout_worker import (
    initialize_trainer,
    vLLMRollout,
    wait_for_rollout_worker,
)
from scale_rl.replay_buffer import ReplayBuffer
from scale_rl.trainer.dp_utils import prepare_dp_model
from scale_rl.trainer.config import TrainerConfig




# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------

class Trainer:
    """
    Owns the FSDP model, optimizer, replay buffer, and the NCCL group used
    to push weights into the vLLM rollout worker.

    Parameters
    ----------
    cfg:
        ``TrainerConfig`` instance.
    device_mesh:
        ``DeviceMesh`` constructed before calling ``__init__``, e.g.::

            mesh = dist.device_mesh.init_device_mesh("cuda", (world_size,))
    model_update_group:
        NCCL process group shared between trainer ranks and the vLLM worker.
        Build with ``dist.new_group([...])`` after ``dist.init_process_group``.
    """

    def __init__(
        self,
        cfg: TrainerConfig,
        device_mesh: Any,
    ) -> None:
        self.cfg = cfg
        self.device = torch.device("cuda", int(os.environ.get("LOCAL_RANK", 0)))
        self.rank = int(os.environ.get("RANK", 0))

        self.tokenizer = AutoTokenizer.from_pretrained(cfg.model_path)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        base_model = AutoModelForCausalLM.from_pretrained(
            cfg.model_path,
            dtype=getattr(torch, cfg.dtype),
        )
        self.model: nn.Module = prepare_dp_model(
            base_model,
            dtype=cfg.dtype,
            sync_module_states=cfg.sync_module_states,
            device_mesh=device_mesh,
            sharding_strategy=cfg.fsdp_sharding_strategy,
        )

        if cfg.gradient_checkpointing:
            self.model.gradient_checkpointing_enable(
                gradient_checkpointing_kwargs={"use_reentrant": False}
            )

        self.optimizer = torch.optim.AdamW(
            self.model.parameters(),
            lr=cfg.lr,
            weight_decay=cfg.weight_decay,
        )

        self.rollout_worker = vLLMRollout(cfg.rollout_worker_url, self.tokenizer)

        # Initialized in train() after rendezvous with the vLLM worker.
        self.model_update_group: Any = None
        # False when FSDP uses NO_SHARD (world_size=1) — parameters keep their
        # original names and don't need full_tensor() gathering.
        self._use_fsdp_gather: bool = False

        self.buffer = ReplayBuffer(
            prompts_per_batch=cfg.prompts_per_batch,
            rollouts_per_step=cfg.rollouts_per_step,
            stale_steps=cfg.stale_steps,
            rollout_worker=self.rollout_worker,
        )

        if cfg.algorithm not in ALGORITHMS:
            raise ValueError(
                f"Unknown algorithm {cfg.algorithm!r}. "
                f"Choose from: {list(ALGORITHMS)}"
            )
        self._loss_fn = ALGORITHMS[cfg.algorithm]

    # ------------------------------------------------------------------
    # Single gradient update
    # ------------------------------------------------------------------

    def step(self, batch: dict[str, Any]) -> dict[str, float]:
        """
        Run one gradient update from a buffer batch.

        Parameters
        ----------
        batch:
            Dict returned by ``ReplayBuffer.sample()``:
            ``{"rollouts": [...], "rewards": [...]}``.

        Returns
        -------
        Metrics dict (loss + algorithm-specific diagnostics).
        """
        cfg = self.cfg

        tensors = prepare_batch(
            batch["rollouts"],
            batch["rewards"],
            self.tokenizer,
            cfg.max_seq_len,
            self.device,
        )
        tensors["advantages"] = compute_advantages(
            cfg.algorithm,
            tensors["rewards"],
            num_samples_per_prompt=cfg.rollouts_per_step,
        )
        rewards = tensors["rewards"]

        # Split into micro-batches for gradient accumulation to save memory.
        B = tensors.batch_size[0]
        accum_steps = cfg.gradient_accumulation_steps
        micro_size = max(1, B // accum_steps)

        self.optimizer.zero_grad()
        total_loss = 0.0
        micro_clip_frac = 0.0

        for micro_start in range(0, B, micro_size):
            micro_end = min(micro_start + micro_size, B)
            micro_tensors = tensors[micro_start:micro_end]
            micro_adv = micro_tensors["advantages"]

            logprobs, response_mask = get_logprobs(
                self.model, micro_tensors, chunk_size=cfg.logprob_chunk_size
            )

            loss = self._loss_fn(
                logprobs=logprobs,
                old_logprobs=micro_tensors["inference_logprobs"],
                advantages=micro_adv,
                response_mask=response_mask,
                clip=cfg.clip_eps,
                clip_low=cfg.clip_low,
                clip_high=cfg.clip_high,
                kl_coeff=cfg.kl_coef,
                inference_logprobs=micro_tensors["inference_logprobs"],
                C=cfg.tis_C,
            )

            scaled_loss = loss / accum_steps
            scaled_loss.backward()
            total_loss += loss.detach().item()

            with torch.no_grad():
                ratio = (logprobs - micro_tensors["inference_logprobs"]).exp()
                mask = response_mask.float()
                n_tok = mask.sum().clamp(min=1)
                micro_clip_frac = (
                    ((ratio < 1 - cfg.clip_eps) | (ratio > 1 + cfg.clip_eps))
                    .float().mul(mask).sum() / n_tok
                ).item()

        nn.utils.clip_grad_norm_(self.model.parameters(), cfg.max_grad_norm)
        self.optimizer.step()

        metrics = {
            "loss": total_loss / accum_steps,
            "clip_frac": micro_clip_frac,
            "mean_reward": rewards.mean().item(),
        }

        if self.rank == 0:
            step = self.buffer.trainer_steps + 1  # +1: incremented inside on_trainer_step
            logger.info(
                f"[trainer step {step}] loss={metrics['loss']:.4f}  "
                f"clip_frac={metrics['clip_frac']:.3f}  "
                f"mean_reward={metrics['mean_reward']:.4f}  algorithm={cfg.algorithm}"
            )

        synced = self.buffer.on_trainer_step(
            self.model,
            self.model_update_group,
            packed=cfg.weight_transfer_packed,
            fsdp=self._use_fsdp_gather,
            clear_kv_cache=cfg.vllm_clear_kv_cache,
        )
        if synced and self.rank == 0:
            logger.info(
                f"[weight sync] trainer step {self.buffer.trainer_steps} → vLLM  "
                f"(every {cfg.stale_steps} steps, packed={cfg.weight_transfer_packed}, fsdp=True)"
            )

        return metrics

    # ------------------------------------------------------------------
    # Full training loop
    # ------------------------------------------------------------------

    def train(self, envs: list[Any], prompts: list[str]) -> None:
        """
        End-to-end training loop.

        Parameters
        ----------
        envs:
            ``ScaleRLBase`` environment instances — one per entry in ``prompts``.
            Used only for reward computation.
        prompts:
            Raw text prompts cycled through during training.
        """
        cfg = self.cfg
        assert len(envs) == len(prompts), "envs and prompts must be the same length"

        if self.rank == 0:
            wait_for_rollout_worker(cfg.rollout_worker_url)

        # ---- wandb (rank 0 only) ----
        if self.rank == 0 and cfg.wandb_enabled:
            wandb.init(
                project=cfg.wandb_project,
                name=cfg.wandb_run_name or None,
                config={
                    "algorithm": cfg.algorithm,
                    "model_path": cfg.model_path,
                    "lr": cfg.lr,
                    "clip_eps": cfg.clip_eps,
                    "clip_low": cfg.clip_low,
                    "clip_high": cfg.clip_high,
                    "kl_coef": cfg.kl_coef,
                    "tis_C": cfg.tis_C,
                    "prompts_per_batch": cfg.prompts_per_batch,
                    "rollouts_per_step": cfg.rollouts_per_step,
                    "stale_steps": cfg.stale_steps,
                    "max_seq_len": cfg.max_seq_len,
                    "max_new_tokens": cfg.max_new_tokens,
                    "temperature": cfg.temperature,
                    "high_pass_rate_threshold": cfg.high_pass_rate_threshold,
                    "low_pass_rate_threshold": cfg.low_pass_rate_threshold,
                    "total_steps": cfg.total_steps,
                },
            )
            logger.info(f"Wandb run initialised: project={cfg.wandb_project} run={wandb.run.name}")

        # Tell the vLLM worker to open its end of the NCCL rendezvous (async on
        # the worker side), then immediately open the trainer end.  Both sides
        # rendezvous on master_address:master_port; trainer is rank 0, vLLM is
        # rank <rank_offset>.  The result is a PyNcclCommunicator whose
        # .broadcast() accepts the src= / stream= kwargs that vLLM expects.
        trainer_world_size = dist.get_world_size()
        nccl_world_size = trainer_world_size + 1  # +1 for the vLLM worker

        # NO_SHARD keeps original parameter names; all sharding strategies that
        # actually shard parameters need full_tensor() gathering before transfer.
        use_fsdp_gather = cfg.fsdp_sharding_strategy != "no_shard"
        self._use_fsdp_gather = use_fsdp_gather

        # ---- Initial weight sync: trainer → vLLM ----
        # Only rank 0 drives HTTP and NCCL; other ranks wait at the barrier.
        # This guarantees vLLM serves the trainer's weights on the very first
        # rollout request — not whatever the vLLM worker loaded from disk.
        if self.rank == 0:
            # initialize_weight_transfer's HTTP call blocks server-side until
            # the vLLM worker's NCCL rendezvous connects — and that rendezvous
            # needs the trainer (rank 0) to dial in via initialize_trainer.
            # Awaiting the HTTP call to completion before starting
            # initialize_trainer would deadlock: each side would be waiting
            # for the other to go first. Run them concurrently instead.
            async def _rendezvous() -> Any:
                _, model_update_group = await asyncio.gather(
                    self.rollout_worker.initialize_weight_transfer(
                        master_address=cfg.master_address,
                        master_port=cfg.weight_transfer_port,
                        rank_offset=trainer_world_size,
                        world_size=nccl_world_size,
                    ),
                    asyncio.to_thread(
                        initialize_trainer,
                        cfg.master_address,
                        cfg.weight_transfer_port,
                        nccl_world_size,
                    ),
                )
                return model_update_group

            self.model_update_group = asyncio.run(_rendezvous())
            logger.info("Performing initial weight sync: trainer → vLLM ...")
            asyncio.run(self.rollout_worker.update_weights(
                self.model,
                self.model_update_group,
                packed=cfg.weight_transfer_packed,
                fsdp=use_fsdp_gather,
            ))
            logger.info("Initial weight sync complete. vLLM is now in sync with the trainer.")

        # All ranks wait here so no rollout is requested until rank 0 has
        # finished pushing weights into the vLLM worker.
        dist.barrier()

        global_step = 0
        prompt_idx = 0

        while global_step < cfg.total_steps:
            # Refresh active pool each round (flags may have been set last round).
            active_indices = [
                i for i, e in enumerate(envs)
                if e.high_pass_rate is None and e.low_pass_rate is None
            ]
            if not active_indices:
                if self.rank == 0:
                    logger.warning(
                        f"All {len(envs)} prompts have been filtered out — nothing left to train on."
                    )
                break

            # ---- generate rollouts (rank 0 drives the HTTP call) ----
            # Cycle through the active pool only.
            n_active = len(active_indices)
            batch_indices = [
                active_indices[(prompt_idx + i) % n_active]
                for i in range(cfg.prompts_per_batch)
            ]
            batch_prompts = [prompts[i] for i in batch_indices]
            batch_envs   = [envs[i]    for i in batch_indices]
            prompt_idx   += cfg.prompts_per_batch

            if self.rank == 0:
                sampling_params = {
                    "max_tokens": cfg.max_new_tokens,
                    "temperature": cfg.temperature,
                    "top_k": cfg.top_k,
                    "logprobs": 1,
                }
                rollouts = asyncio.run(self.rollout_worker.generate_batch(
                    batch_prompts,
                    num_samples=cfg.rollouts_per_step,
                    sampling_params=sampling_params,
                ))
                # Rollouts are ordered: [prompt_0 × G, prompt_1 × G, ...]
                rewards: list[float] = []
                for i, env in enumerate(batch_envs):
                    group_rewards: list[float] = []
                    n_truncated = 0
                    for g in range(cfg.rollouts_per_step):
                        record = rollouts[i * cfg.rollouts_per_step + g]
                        reward, _ = env.compute_reward(record.response)
                        rewards.append(reward)
                        group_rewards.append(reward)
                        if record.response_record.finish_reason == "length":
                            n_truncated += 1

                    pass_rate = sum(group_rewards) / len(group_rewards)
                    if pass_rate >= cfg.high_pass_rate_threshold and env.high_pass_rate is None:
                        env.high_pass_rate = pass_rate
                        logger.info(f"[high_pass_rate] prompt idx={batch_indices[i]} marked — pass_rate={pass_rate:.2f} >= {cfg.high_pass_rate_threshold:.2f}, will be skipped henceforth.")
                    elif 0 < cfg.low_pass_rate_threshold >= pass_rate and env.low_pass_rate is None:
                        env.low_pass_rate = pass_rate
                        logger.info(f"[low_pass_rate] prompt idx={batch_indices[i]} marked — pass_rate={pass_rate:.2f} <= {cfg.low_pass_rate_threshold:.2f} ({n_truncated}/{cfg.rollouts_per_step} hit max_new_tokens), will be skipped henceforth.")

                n_high_filtered = sum(1 for e in envs if e.high_pass_rate is not None)
                n_low_filtered = sum(1 for e in envs if e.low_pass_rate is not None)
                logger.info(
                    f"[filter] {n_high_filtered} too easy, {n_low_filtered} too hard, "
                    f"{len(envs) - n_high_filtered - n_low_filtered}/{len(envs)} active."
                )
                if cfg.wandb_enabled:
                    wandb.log(
                        {
                            "data/high_pass_rate_filtered": n_high_filtered,
                            "data/low_pass_rate_filtered": n_low_filtered,
                            "data/active_prompts": len(envs) - n_high_filtered - n_low_filtered,
                        },
                        step=global_step,
                    )

                self.buffer.add(rollouts, rewards)

            # Ensure all ranks wait for rank-0 to finish collecting.
            dist.barrier()

            # ---- drain the buffer ----
            while self.buffer.is_ready():
                batch = self.buffer.sample()
                metrics = self.step(batch)
                global_step += 1

                if self.rank == 0:
                    if cfg.wandb_enabled:
                        wandb.log(
                            {
                                "train/loss": metrics["loss"],
                                "train/clip_frac": metrics["clip_frac"],
                                "train/mean_reward": metrics["mean_reward"],
                                "train/trainer_steps": self.buffer.trainer_steps,
                            },
                            step=global_step,
                        )

                    if global_step % cfg.log_every == 0:
                        logger.info(
                            f"step={global_step}  loss={metrics['loss']:.4f}  "
                            f"clip_frac={metrics['clip_frac']:.3f}  "
                            f"mean_reward={metrics['mean_reward']:.4f}"
                        )

                if cfg.eval_every > 0 and global_step % cfg.eval_every == 0:
                    if self.rank == 0:
                        env_cls = DATASET_ENV_CLS[cfg.dataset]
                        env_cls.evaluate(
                            rollout_worker=self.rollout_worker,
                            step=global_step,
                            eval_k=cfg.eval_k,
                            eval_max_tokens=cfg.eval_max_tokens,
                            temperature=cfg.eval_temperature,
                            top_k=cfg.eval_top_k,
                        )
                    dist.barrier()

                if global_step >= cfg.total_steps:
                    break

        if self.rank == 0 and cfg.wandb_enabled:
            wandb.finish()
            logger.info("Wandb run finished.")
